[project]
name = "c4bot-ce"
version = "1.1.0"
description = "Discord Youtube bot"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "discord-py>=2.6.4",
    "pynacl>=1.6.1",
    "python-dotenv>=1.2.1",
    "yt-dlp>=2025.12.8",
]
